adminUser:
  password: admin
  username: admin
enableDocker: true
pipelineUser:
  email: ivycx1992@gmail.com
  token: local:jenkins-x-test-keep/pipelineUser:token
  username: evincai
prow:
  hmacToken: local:jenkins-x-test-keep/prow:hmacToken
